require 'rubygems'
require 'rake'
require 'rspec/core/rake_task'

ENV["env"] ||= 'stg'

desc "Run Bifrost tests"
RSpec::Core::RakeTask.new('bifrost') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'spec/bifrost/**/*.rb'
end

desc "Run Bifrost tests without format documentation"
RSpec::Core::RakeTask.new('bifrost-nodoc') do |t|
  t.rspec_opts = ["-Ilib","--color"]
  t.pattern = 'spec/bifrost/**/*.rb'
end

desc "Run Bifrost user flow tests"
RSpec::Core::RakeTask.new('bifrost-user-flows') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'spec/bifrost/_user_flows/**/*.rb'
end

desc "Run Bifrost concept lists tests"
RSpec::Core::RakeTask.new('bifrost-concpet-lists') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'spec/bifrost/_concept_lists/**/*.rb'
end

desc "Run Veggr tests"
RSpec::Core::RakeTask.new('veggr') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'spec/veggr/**/*.rb'
end

desc "Run Idun tests"
RSpec::Core::RakeTask.new('idun') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'spec/idun/**/*.rb'
end

desc "Run Helloreverb.com tests"
RSpec::Core::RakeTask.new('helloreverb') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'spec/helloreverb/**/*.rb'
end

desc "Run Helloreverb.com tests without format documentation"
RSpec::Core::RakeTask.new('helloreverb-nodoc') do |t|
  t.rspec_opts = ["-Ilib","--color"]
  t.pattern = 'spec/helloreverb/**/*.rb'
end
