dev:
  baseurl: dev-api.helloreverb.com/v2

stg:
  baseurl: stage-api.helloreverb.com/v2

prd:
  baseurl: api.helloreverb.com/v2

basil:
  baseurl: basil-api.helloreverb.com/v2

anise:
  baseurl: anise-api.helloreverb.com/v2

thyme:
  baseurl: thyme-api.helloreverb.com/v2

nutmeg:
  baseurl: nutmeg-api.helloreverb.com/v2