dev:
  baseurl: dev-images.helloreverb.com

stg:
  baseurl: stage-images.helloreverb.com

prd:
  baseurl: images.helloreverb.com

basil:
  baseurl: basil-images.helloreverb.com

anise:
  baseurl: anise-images.helloreverb.com

thyme:
  baseurl: thyme-images.helloreverb.com

nutmeg:
  baseurl: nutmeg-images.helloreverb.com/v2